version: 0.0
os: linux
files:
  - source: "/"
    destination: "/tmp"
hooks:
  ApplicationStop:
    - location: codedeployScripts/app_stop.sh 
      timeout: 300
      runas: root
  BeforeInstall:
    - location: codedeployScripts/before_install.sh 
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeployScripts/after_install.sh 
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeployScripts/app_start.sh 
      timeout: 300
      runas: root
  ValidateService:
    - location: codedeployScripts/validate_service.sh 
      timeout: 300
      runas: root